# Generated by Django 5.1.5 on 2025-02-05 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PageVisits',
            new_name='PageVisit',
        ),
    ]
